CREATE TABLE IF NOT EXISTS report_project (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    project_key VARCHAR(64) NOT NULL,
    project_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    trusted_token_secret VARCHAR(256) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_project_key (project_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS error_issue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    group_fingerprint CHAR(64) NOT NULL,
    category VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    title VARCHAR(512) NOT NULL,
    normalized_message VARCHAR(512) NOT NULL DEFAULT '',
    normalized_stack_top VARCHAR(512) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'open',
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    total_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_release VARCHAR(64) NOT NULL DEFAULT '',
    last_language VARCHAR(16) NOT NULL DEFAULT 'unknown',
    last_platform VARCHAR(32) NOT NULL DEFAULT 'unknown',
    sample_event_id VARCHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_project_fingerprint (project_id, group_fingerprint),
    KEY idx_project_status (project_id, status),
    KEY idx_last_seen (last_seen_at),
    CONSTRAINT fk_issue_project FOREIGN KEY (project_id) REFERENCES report_project(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS error_event (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    issue_id BIGINT UNSIGNED NOT NULL,
    release_fingerprint CHAR(64) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    `release` VARCHAR(64) NOT NULL,
    env VARCHAR(16) NOT NULL,
    category VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    message VARCHAR(512) NOT NULL,
    stack TEXT,
    route VARCHAR(256) NOT NULL DEFAULT '',
    scene VARCHAR(128) NOT NULL DEFAULT '',
    module VARCHAR(256) NOT NULL DEFAULT '',
    language VARCHAR(16) NOT NULL DEFAULT 'unknown',
    runtime VARCHAR(32) NOT NULL DEFAULT '',
    user_id VARCHAR(128) NOT NULL DEFAULT '',
    room_id VARCHAR(128) NOT NULL DEFAULT '',
    session_id VARCHAR(128) NOT NULL DEFAULT '',
    device_platform VARCHAR(32) NOT NULL DEFAULT 'unknown',
    device_model VARCHAR(128) NOT NULL DEFAULT 'unknown',
    os_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
    sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
    network_type VARCHAR(32) NOT NULL DEFAULT 'unknown',
    api_method VARCHAR(16) NOT NULL DEFAULT '',
    api_path VARCHAR(512) NOT NULL DEFAULT '',
    http_status INT NOT NULL DEFAULT 0,
    ws_phase VARCHAR(32) NOT NULL DEFAULT '',
    ws_code INT NOT NULL DEFAULT 0,
    ws_reason VARCHAR(256) NOT NULL DEFAULT '',
    asset_type VARCHAR(32) NOT NULL DEFAULT '',
    asset_path VARCHAR(512) NOT NULL DEFAULT '',
    asset_url VARCHAR(1024) NOT NULL DEFAULT '',
    biz_code VARCHAR(128) NOT NULL DEFAULT '',
    extra_json JSON,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_event_id (event_id),
    KEY idx_issue_occurred (issue_id, occurred_at),
    KEY idx_project_occurred (project_id, occurred_at),
    CONSTRAINT fk_event_project FOREIGN KEY (project_id) REFERENCES report_project(id),
    CONSTRAINT fk_event_issue FOREIGN KEY (issue_id) REFERENCES error_issue(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS error_issue_release_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    issue_id BIGINT UNSIGNED NOT NULL,
    `release` VARCHAR(64) NOT NULL,
    stat_date DATE NOT NULL,
    event_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    first_seen_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_issue_release_date (issue_id, `release`, stat_date),
    CONSTRAINT fk_daily_issue FOREIGN KEY (issue_id) REFERENCES error_issue(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
