CREATE TABLE IF NOT EXISTS user_feedback (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    feedback_id VARCHAR(64) NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    submitted_at DATETIME(3) NOT NULL,
    `release` VARCHAR(64) NOT NULL,
    env VARCHAR(16) NOT NULL,
    category VARCHAR(32) NOT NULL DEFAULT 'other',
    content TEXT NOT NULL,
    contact VARCHAR(256) NOT NULL DEFAULT '',
    route VARCHAR(256) NOT NULL DEFAULT '',
    scene VARCHAR(128) NOT NULL DEFAULT '',
    language VARCHAR(16) NOT NULL DEFAULT 'unknown',
    runtime VARCHAR(32) NOT NULL DEFAULT '',
    user_id VARCHAR(128) NOT NULL DEFAULT '',
    room_id VARCHAR(128) NOT NULL DEFAULT '',
    session_id VARCHAR(128) NOT NULL DEFAULT '',
    device_platform VARCHAR(32) NOT NULL DEFAULT 'unknown',
    device_model VARCHAR(128) NOT NULL DEFAULT 'unknown',
    os_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
    sdk_version VARCHAR(64) NOT NULL DEFAULT 'unknown',
    network_type VARCHAR(32) NOT NULL DEFAULT 'unknown',
    extra_json JSON,
    status VARCHAR(16) NOT NULL DEFAULT 'open',
    admin_note TEXT,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_feedback_id (feedback_id),
    KEY idx_feedback_project_submitted (project_id, submitted_at),
    KEY idx_feedback_status (project_id, status, submitted_at),
    CONSTRAINT fk_feedback_project FOREIGN KEY (project_id) REFERENCES report_project(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
