services:
  eventhub:
    image: jpccr.ccs.tencentyun.com/eventhub/eventhub:${EVENTHUB_VERSION}
    restart: unless-stopped
    ports:
      - "6185:8080"
    env_file:
      - ./config/.env
    environment:
      HTTP_ADDR: ":8080"
    volumes:
      - ./data/log:/app/log
      - ./config:/app/config
